workspace:
  base: /go
  path: src/github.com/honestbee/drone-helm

pipeline:
  test:
    image: golang:1.8
    commands:
      - go get
      - go get github.com/mattn/goveralls
      - goveralls 
    secrets:
      - coveralls_token

  compile:
    image: golang:1.8
    commands:
      - export PATH=$PATH:/go/bin
      - mkdir bin
      - go build -a -tags netgo -ldflags "-s -w -X main.build=${DRONE_BUILD_NUMBER}" -o bin/drone-helm

  publish:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/honestbee/drone-helm
    tags: 
      - "latest"
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}
    secrets:
      - docker_password
      - docker_username
      - docker_registry
    when:
      branch: [master, add-repo-support, use-debian-as-base]

  notify:
    image: plugins/slack
    channel: feed-devops
    secrets:
      - slack_webhook
    when:
      status: [ success, failure ]

